[versions]
kotlin = "1.7.0"

[libraries]
animalsniffer-signature-android = "net.sf.androidscents.signature:android-api-level-23:6.0_r3"
hkdf = "at.favre.lib:hkdf:1.1.0"
kotlintest-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[plugins]
animalsniffer = "ru.vyarus.animalsniffer:1.5.4"
dokka = "org.jetbrains.dokka:1.6.21"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = "com.diffplug.spotless:6.7.2"
vcu = "nl.littlerobots.version-catalog-update:0.5.1"
versions = "com.github.ben-manes.versions:0.42.0"
