[versions]
junit = "5.9.2"
kotlin = "1.8.20"

[libraries]
animalsniffer-signature-android = "net.sf.androidscents.signature:android-api-level-23:6.0_r3"
bouncycastle-bcprov = "org.bouncycastle:bcprov-jdk15to18:1.73"
hkdf = "at.favre.lib:hkdf:2.0.0"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-legacy = "junit:junit:4.13.2"
kotlinresult = "com.michael-bull.kotlin-result:kotlin-result:1.1.17"
kotlintest-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
truth = "com.google.truth:truth:1.1.3"

[plugins]
animalsniffer = "ru.vyarus.animalsniffer:1.7.0"
dokka = "org.jetbrains.dokka:1.8.10"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = "org.jetbrains.kotlinx.kover:0.6.1"
mavenPublish = "com.vanniktech.maven.publish:0.25.1"
spotless = "com.diffplug.spotless:6.18.0"
vcu = "nl.littlerobots.version-catalog-update:0.8.0"
versions = "com.github.ben-manes.versions:0.46.0"
