[versions]
junit = "5.11.2"
kotlin = "2.0.21"

[libraries]
animalsniffer-signature-android = "net.sf.androidscents.signature:android-api-level-23:6.0_r3"
bouncycastle-bcprov = "org.bouncycastle:bcprov-jdk15to18:1.78.1"
hkdf = "at.favre.lib:hkdf:2.0.0"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-legacy = "junit:junit:4.13.2"
kotlinresult = "com.michael-bull.kotlin-result:kotlin-result:2.0.0"
kotlintest-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
truth = "com.google.truth:truth:1.4.4"

[plugins]
animalsniffer = "ru.vyarus.animalsniffer:1.7.1"
dokka = "org.jetbrains.dokka:1.9.20"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = "org.jetbrains.kotlinx.kover:0.8.3"
mavenPublish = "com.vanniktech.maven.publish:0.29.0"
spotless = "com.diffplug.spotless:6.25.0"
vcu = "nl.littlerobots.version-catalog-update:0.8.4"
versions = "com.github.ben-manes.versions:0.51.0"
