[versions]
junit = "5.9.1"
kotlin = "1.7.22"

[libraries]
animalsniffer-signature-android = "net.sf.androidscents.signature:android-api-level-23:6.0_r3"
bouncycastle-bcprov = "org.bouncycastle:bcprov-jdk15to18:1.72"
hkdf = "at.favre.lib:hkdf:1.1.0"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
kotlintest-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinresult = "com.michael-bull.kotlin-result:kotlin-result:1.1.16"
truth = "com.google.truth:truth:1.1.3"

[plugins]
animalsniffer = "ru.vyarus.animalsniffer:1.6.0"
dokka = "org.jetbrains.dokka:1.7.20"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = "com.diffplug.spotless:6.12.0"
vcu = "nl.littlerobots.version-catalog-update:0.7.0"
versions = "com.github.ben-manes.versions:0.44.0"
